// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: proto/record.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecordService_ListThoughtRecords_FullMethodName     = "/record.RecordService/ListThoughtRecords"
	RecordService_CreateThoughtRecord_FullMethodName    = "/record.RecordService/CreateThoughtRecord"
	RecordService_GetThoughtRecord_FullMethodName       = "/record.RecordService/GetThoughtRecord"
	RecordService_UpdateThoughtRecord_FullMethodName    = "/record.RecordService/UpdateThoughtRecord"
	RecordService_ChallengeThoughtRecord_FullMethodName = "/record.RecordService/ChallengeThoughtRecord"
	RecordService_DeleteThoughtRecord_FullMethodName    = "/record.RecordService/DeleteThoughtRecord"
	RecordService_AddThought_FullMethodName             = "/record.RecordService/AddThought"
	RecordService_UpdateThought_FullMethodName          = "/record.RecordService/UpdateThought"
	RecordService_SetHotThought_FullMethodName          = "/record.RecordService/SetHotThought"
	RecordService_SetThoughtFactual_FullMethodName      = "/record.RecordService/SetThoughtFactual"
	RecordService_DeleteThought_FullMethodName          = "/record.RecordService/DeleteThought"
	RecordService_AddFeeling_FullMethodName             = "/record.RecordService/AddFeeling"
	RecordService_AddMapFeeling_FullMethodName          = "/record.RecordService/AddMapFeeling"
	RecordService_DeleteFeeling_FullMethodName          = "/record.RecordService/DeleteFeeling"
	RecordService_ListMapsOfWorry_FullMethodName        = "/record.RecordService/ListMapsOfWorry"
	RecordService_CreateMapOfWorry_FullMethodName       = "/record.RecordService/CreateMapOfWorry"
	RecordService_GetMapOfWorry_FullMethodName          = "/record.RecordService/GetMapOfWorry"
	RecordService_UpdateMapOfWorry_FullMethodName       = "/record.RecordService/UpdateMapOfWorry"
	RecordService_DeleteMapOfWorry_FullMethodName       = "/record.RecordService/DeleteMapOfWorry"
	RecordService_ListBiases_FullMethodName             = "/record.RecordService/ListBiases"
	RecordService_CreateBias_FullMethodName             = "/record.RecordService/CreateBias"
	RecordService_RenameBias_FullMethodName             = "/record.RecordService/RenameBias"
	RecordService_DeleteBias_FullMethodName             = "/record.RecordService/DeleteBias"
)

// RecordServiceClient is the client API for RecordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RecordService is the gRPC API served by `cbt serve`. RPCs are added here and
// registered in cmd/serve.go.
//
// Both record types and the cognitive bias vocabulary live on a single service
// rather than one service per entity: the client wrapper and the interceptor
// wiring would otherwise be duplicated for no gain, and listing across both
// record types needs a single endpoint anyway.
type RecordServiceClient interface {
	// ListThoughtRecords returns the user's thought records, most recent event
	// first. Filtering by challenged = false yields the day's work queue.
	ListThoughtRecords(ctx context.Context, in *ListThoughtRecordsRequest, opts ...grpc.CallOption) (*ListThoughtRecordsResponse, error)
	// CreateThoughtRecord creates a record. Only the event is required: a record
	// is routinely opened in the moment and completed later.
	CreateThoughtRecord(ctx context.Context, in *CreateThoughtRecordRequest, opts ...grpc.CallOption) (*ThoughtRecord, error)
	// GetThoughtRecord returns a single record by identifier.
	GetThoughtRecord(ctx context.Context, in *GetThoughtRecordRequest, opts ...grpc.CallOption) (*ThoughtRecord, error)
	// UpdateThoughtRecord changes the free text columns of a record. Fields left
	// unset keep their current value.
	UpdateThoughtRecord(ctx context.Context, in *UpdateThoughtRecordRequest, opts ...grpc.CallOption) (*ThoughtRecord, error)
	// ChallengeThoughtRecord records the second sitting: the alternative view,
	// the re-rating of each feeling, and the biases identified in each thought.
	// It stamps challenged_at so the record leaves the unchallenged queue.
	ChallengeThoughtRecord(ctx context.Context, in *ChallengeThoughtRecordRequest, opts ...grpc.CallOption) (*ThoughtRecord, error)
	// DeleteThoughtRecord removes a record along with its thoughts and feelings.
	DeleteThoughtRecord(ctx context.Context, in *DeleteThoughtRecordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// AddThought attaches a further negative thought to a record.
	AddThought(ctx context.Context, in *AddThoughtRequest, opts ...grpc.CallOption) (*ThoughtRecord, error)
	// UpdateThought changes the wording of a thought and, optionally, the biases
	// attached to it.
	UpdateThought(ctx context.Context, in *UpdateThoughtRequest, opts ...grpc.CallOption) (*ThoughtRecord, error)
	// SetHotThought marks a thought as the strongest of its record, clearing the
	// flag from its siblings.
	SetHotThought(ctx context.Context, in *SetHotThoughtRequest, opts ...grpc.CallOption) (*ThoughtRecord, error)
	// SetThoughtFactual records whether a thought was judged an accurate reading
	// of the situation. Marking one factual while it carries a bias is rejected.
	SetThoughtFactual(ctx context.Context, in *SetThoughtFactualRequest, opts ...grpc.CallOption) (*ThoughtRecord, error)
	// DeleteThought removes a thought from its record.
	DeleteThought(ctx context.Context, in *DeleteThoughtRequest, opts ...grpc.CallOption) (*ThoughtRecord, error)
	// AddFeeling attaches a rated feeling to a thought record.
	AddFeeling(ctx context.Context, in *AddFeelingRequest, opts ...grpc.CallOption) (*ThoughtRecord, error)
	// AddMapFeeling attaches a rated feeling to a map of worry.
	AddMapFeeling(ctx context.Context, in *AddMapFeelingRequest, opts ...grpc.CallOption) (*MapOfWorry, error)
	// DeleteFeeling removes a feeling from whichever record it belongs to.
	DeleteFeeling(ctx context.Context, in *DeleteFeelingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListMapsOfWorry returns the user's maps of worry, most recent event first.
	ListMapsOfWorry(ctx context.Context, in *ListMapsOfWorryRequest, opts ...grpc.CallOption) (*ListMapsOfWorryResponse, error)
	// CreateMapOfWorry creates a map. Setting derived_from_id marks it as an
	// alternative reworking of an existing map, to be read alongside it.
	CreateMapOfWorry(ctx context.Context, in *CreateMapOfWorryRequest, opts ...grpc.CallOption) (*MapOfWorry, error)
	// GetMapOfWorry returns a single map together with the map it was derived
	// from and any alternatives derived from it.
	GetMapOfWorry(ctx context.Context, in *GetMapOfWorryRequest, opts ...grpc.CallOption) (*GetMapOfWorryResponse, error)
	// UpdateMapOfWorry changes the free text columns of a map.
	UpdateMapOfWorry(ctx context.Context, in *UpdateMapOfWorryRequest, opts ...grpc.CallOption) (*MapOfWorry, error)
	// DeleteMapOfWorry removes a map along with its feelings. A map with
	// alternatives derived from it is rejected.
	DeleteMapOfWorry(ctx context.Context, in *DeleteMapOfWorryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListBiases returns the user's cognitive bias vocabulary, ordered by name.
	ListBiases(ctx context.Context, in *ListBiasesRequest, opts ...grpc.CallOption) (*ListBiasesResponse, error)
	// CreateBias adds a user defined bias alongside the seeded ones.
	CreateBias(ctx context.Context, in *CreateBiasRequest, opts ...grpc.CallOption) (*CognitiveBias, error)
	// RenameBias renames a user defined bias. Builtin biases are rejected.
	RenameBias(ctx context.Context, in *RenameBiasRequest, opts ...grpc.CallOption) (*CognitiveBias, error)
	// DeleteBias removes a user defined bias that is no longer in use.
	DeleteBias(ctx context.Context, in *DeleteBiasRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type recordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordServiceClient(cc grpc.ClientConnInterface) RecordServiceClient {
	return &recordServiceClient{cc}
}

func (c *recordServiceClient) ListThoughtRecords(ctx context.Context, in *ListThoughtRecordsRequest, opts ...grpc.CallOption) (*ListThoughtRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListThoughtRecordsResponse)
	err := c.cc.Invoke(ctx, RecordService_ListThoughtRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) CreateThoughtRecord(ctx context.Context, in *CreateThoughtRecordRequest, opts ...grpc.CallOption) (*ThoughtRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThoughtRecord)
	err := c.cc.Invoke(ctx, RecordService_CreateThoughtRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) GetThoughtRecord(ctx context.Context, in *GetThoughtRecordRequest, opts ...grpc.CallOption) (*ThoughtRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThoughtRecord)
	err := c.cc.Invoke(ctx, RecordService_GetThoughtRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) UpdateThoughtRecord(ctx context.Context, in *UpdateThoughtRecordRequest, opts ...grpc.CallOption) (*ThoughtRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThoughtRecord)
	err := c.cc.Invoke(ctx, RecordService_UpdateThoughtRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) ChallengeThoughtRecord(ctx context.Context, in *ChallengeThoughtRecordRequest, opts ...grpc.CallOption) (*ThoughtRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThoughtRecord)
	err := c.cc.Invoke(ctx, RecordService_ChallengeThoughtRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) DeleteThoughtRecord(ctx context.Context, in *DeleteThoughtRecordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RecordService_DeleteThoughtRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) AddThought(ctx context.Context, in *AddThoughtRequest, opts ...grpc.CallOption) (*ThoughtRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThoughtRecord)
	err := c.cc.Invoke(ctx, RecordService_AddThought_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) UpdateThought(ctx context.Context, in *UpdateThoughtRequest, opts ...grpc.CallOption) (*ThoughtRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThoughtRecord)
	err := c.cc.Invoke(ctx, RecordService_UpdateThought_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) SetHotThought(ctx context.Context, in *SetHotThoughtRequest, opts ...grpc.CallOption) (*ThoughtRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThoughtRecord)
	err := c.cc.Invoke(ctx, RecordService_SetHotThought_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) SetThoughtFactual(ctx context.Context, in *SetThoughtFactualRequest, opts ...grpc.CallOption) (*ThoughtRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThoughtRecord)
	err := c.cc.Invoke(ctx, RecordService_SetThoughtFactual_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) DeleteThought(ctx context.Context, in *DeleteThoughtRequest, opts ...grpc.CallOption) (*ThoughtRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThoughtRecord)
	err := c.cc.Invoke(ctx, RecordService_DeleteThought_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) AddFeeling(ctx context.Context, in *AddFeelingRequest, opts ...grpc.CallOption) (*ThoughtRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThoughtRecord)
	err := c.cc.Invoke(ctx, RecordService_AddFeeling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) AddMapFeeling(ctx context.Context, in *AddMapFeelingRequest, opts ...grpc.CallOption) (*MapOfWorry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapOfWorry)
	err := c.cc.Invoke(ctx, RecordService_AddMapFeeling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) DeleteFeeling(ctx context.Context, in *DeleteFeelingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RecordService_DeleteFeeling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) ListMapsOfWorry(ctx context.Context, in *ListMapsOfWorryRequest, opts ...grpc.CallOption) (*ListMapsOfWorryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMapsOfWorryResponse)
	err := c.cc.Invoke(ctx, RecordService_ListMapsOfWorry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) CreateMapOfWorry(ctx context.Context, in *CreateMapOfWorryRequest, opts ...grpc.CallOption) (*MapOfWorry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapOfWorry)
	err := c.cc.Invoke(ctx, RecordService_CreateMapOfWorry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) GetMapOfWorry(ctx context.Context, in *GetMapOfWorryRequest, opts ...grpc.CallOption) (*GetMapOfWorryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMapOfWorryResponse)
	err := c.cc.Invoke(ctx, RecordService_GetMapOfWorry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) UpdateMapOfWorry(ctx context.Context, in *UpdateMapOfWorryRequest, opts ...grpc.CallOption) (*MapOfWorry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapOfWorry)
	err := c.cc.Invoke(ctx, RecordService_UpdateMapOfWorry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) DeleteMapOfWorry(ctx context.Context, in *DeleteMapOfWorryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RecordService_DeleteMapOfWorry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) ListBiases(ctx context.Context, in *ListBiasesRequest, opts ...grpc.CallOption) (*ListBiasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBiasesResponse)
	err := c.cc.Invoke(ctx, RecordService_ListBiases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) CreateBias(ctx context.Context, in *CreateBiasRequest, opts ...grpc.CallOption) (*CognitiveBias, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CognitiveBias)
	err := c.cc.Invoke(ctx, RecordService_CreateBias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) RenameBias(ctx context.Context, in *RenameBiasRequest, opts ...grpc.CallOption) (*CognitiveBias, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CognitiveBias)
	err := c.cc.Invoke(ctx, RecordService_RenameBias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) DeleteBias(ctx context.Context, in *DeleteBiasRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RecordService_DeleteBias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordServiceServer is the server API for RecordService service.
// All implementations must embed UnimplementedRecordServiceServer
// for forward compatibility.
//
// RecordService is the gRPC API served by `cbt serve`. RPCs are added here and
// registered in cmd/serve.go.
//
// Both record types and the cognitive bias vocabulary live on a single service
// rather than one service per entity: the client wrapper and the interceptor
// wiring would otherwise be duplicated for no gain, and listing across both
// record types needs a single endpoint anyway.
type RecordServiceServer interface {
	// ListThoughtRecords returns the user's thought records, most recent event
	// first. Filtering by challenged = false yields the day's work queue.
	ListThoughtRecords(context.Context, *ListThoughtRecordsRequest) (*ListThoughtRecordsResponse, error)
	// CreateThoughtRecord creates a record. Only the event is required: a record
	// is routinely opened in the moment and completed later.
	CreateThoughtRecord(context.Context, *CreateThoughtRecordRequest) (*ThoughtRecord, error)
	// GetThoughtRecord returns a single record by identifier.
	GetThoughtRecord(context.Context, *GetThoughtRecordRequest) (*ThoughtRecord, error)
	// UpdateThoughtRecord changes the free text columns of a record. Fields left
	// unset keep their current value.
	UpdateThoughtRecord(context.Context, *UpdateThoughtRecordRequest) (*ThoughtRecord, error)
	// ChallengeThoughtRecord records the second sitting: the alternative view,
	// the re-rating of each feeling, and the biases identified in each thought.
	// It stamps challenged_at so the record leaves the unchallenged queue.
	ChallengeThoughtRecord(context.Context, *ChallengeThoughtRecordRequest) (*ThoughtRecord, error)
	// DeleteThoughtRecord removes a record along with its thoughts and feelings.
	DeleteThoughtRecord(context.Context, *DeleteThoughtRecordRequest) (*emptypb.Empty, error)
	// AddThought attaches a further negative thought to a record.
	AddThought(context.Context, *AddThoughtRequest) (*ThoughtRecord, error)
	// UpdateThought changes the wording of a thought and, optionally, the biases
	// attached to it.
	UpdateThought(context.Context, *UpdateThoughtRequest) (*ThoughtRecord, error)
	// SetHotThought marks a thought as the strongest of its record, clearing the
	// flag from its siblings.
	SetHotThought(context.Context, *SetHotThoughtRequest) (*ThoughtRecord, error)
	// SetThoughtFactual records whether a thought was judged an accurate reading
	// of the situation. Marking one factual while it carries a bias is rejected.
	SetThoughtFactual(context.Context, *SetThoughtFactualRequest) (*ThoughtRecord, error)
	// DeleteThought removes a thought from its record.
	DeleteThought(context.Context, *DeleteThoughtRequest) (*ThoughtRecord, error)
	// AddFeeling attaches a rated feeling to a thought record.
	AddFeeling(context.Context, *AddFeelingRequest) (*ThoughtRecord, error)
	// AddMapFeeling attaches a rated feeling to a map of worry.
	AddMapFeeling(context.Context, *AddMapFeelingRequest) (*MapOfWorry, error)
	// DeleteFeeling removes a feeling from whichever record it belongs to.
	DeleteFeeling(context.Context, *DeleteFeelingRequest) (*emptypb.Empty, error)
	// ListMapsOfWorry returns the user's maps of worry, most recent event first.
	ListMapsOfWorry(context.Context, *ListMapsOfWorryRequest) (*ListMapsOfWorryResponse, error)
	// CreateMapOfWorry creates a map. Setting derived_from_id marks it as an
	// alternative reworking of an existing map, to be read alongside it.
	CreateMapOfWorry(context.Context, *CreateMapOfWorryRequest) (*MapOfWorry, error)
	// GetMapOfWorry returns a single map together with the map it was derived
	// from and any alternatives derived from it.
	GetMapOfWorry(context.Context, *GetMapOfWorryRequest) (*GetMapOfWorryResponse, error)
	// UpdateMapOfWorry changes the free text columns of a map.
	UpdateMapOfWorry(context.Context, *UpdateMapOfWorryRequest) (*MapOfWorry, error)
	// DeleteMapOfWorry removes a map along with its feelings. A map with
	// alternatives derived from it is rejected.
	DeleteMapOfWorry(context.Context, *DeleteMapOfWorryRequest) (*emptypb.Empty, error)
	// ListBiases returns the user's cognitive bias vocabulary, ordered by name.
	ListBiases(context.Context, *ListBiasesRequest) (*ListBiasesResponse, error)
	// CreateBias adds a user defined bias alongside the seeded ones.
	CreateBias(context.Context, *CreateBiasRequest) (*CognitiveBias, error)
	// RenameBias renames a user defined bias. Builtin biases are rejected.
	RenameBias(context.Context, *RenameBiasRequest) (*CognitiveBias, error)
	// DeleteBias removes a user defined bias that is no longer in use.
	DeleteBias(context.Context, *DeleteBiasRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedRecordServiceServer()
}

// UnimplementedRecordServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordServiceServer struct{}

func (UnimplementedRecordServiceServer) ListThoughtRecords(context.Context, *ListThoughtRecordsRequest) (*ListThoughtRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListThoughtRecords not implemented")
}
func (UnimplementedRecordServiceServer) CreateThoughtRecord(context.Context, *CreateThoughtRecordRequest) (*ThoughtRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateThoughtRecord not implemented")
}
func (UnimplementedRecordServiceServer) GetThoughtRecord(context.Context, *GetThoughtRecordRequest) (*ThoughtRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThoughtRecord not implemented")
}
func (UnimplementedRecordServiceServer) UpdateThoughtRecord(context.Context, *UpdateThoughtRecordRequest) (*ThoughtRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateThoughtRecord not implemented")
}
func (UnimplementedRecordServiceServer) ChallengeThoughtRecord(context.Context, *ChallengeThoughtRecordRequest) (*ThoughtRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method ChallengeThoughtRecord not implemented")
}
func (UnimplementedRecordServiceServer) DeleteThoughtRecord(context.Context, *DeleteThoughtRecordRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteThoughtRecord not implemented")
}
func (UnimplementedRecordServiceServer) AddThought(context.Context, *AddThoughtRequest) (*ThoughtRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method AddThought not implemented")
}
func (UnimplementedRecordServiceServer) UpdateThought(context.Context, *UpdateThoughtRequest) (*ThoughtRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateThought not implemented")
}
func (UnimplementedRecordServiceServer) SetHotThought(context.Context, *SetHotThoughtRequest) (*ThoughtRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method SetHotThought not implemented")
}
func (UnimplementedRecordServiceServer) SetThoughtFactual(context.Context, *SetThoughtFactualRequest) (*ThoughtRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method SetThoughtFactual not implemented")
}
func (UnimplementedRecordServiceServer) DeleteThought(context.Context, *DeleteThoughtRequest) (*ThoughtRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteThought not implemented")
}
func (UnimplementedRecordServiceServer) AddFeeling(context.Context, *AddFeelingRequest) (*ThoughtRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFeeling not implemented")
}
func (UnimplementedRecordServiceServer) AddMapFeeling(context.Context, *AddMapFeelingRequest) (*MapOfWorry, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMapFeeling not implemented")
}
func (UnimplementedRecordServiceServer) DeleteFeeling(context.Context, *DeleteFeelingRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFeeling not implemented")
}
func (UnimplementedRecordServiceServer) ListMapsOfWorry(context.Context, *ListMapsOfWorryRequest) (*ListMapsOfWorryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMapsOfWorry not implemented")
}
func (UnimplementedRecordServiceServer) CreateMapOfWorry(context.Context, *CreateMapOfWorryRequest) (*MapOfWorry, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMapOfWorry not implemented")
}
func (UnimplementedRecordServiceServer) GetMapOfWorry(context.Context, *GetMapOfWorryRequest) (*GetMapOfWorryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMapOfWorry not implemented")
}
func (UnimplementedRecordServiceServer) UpdateMapOfWorry(context.Context, *UpdateMapOfWorryRequest) (*MapOfWorry, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMapOfWorry not implemented")
}
func (UnimplementedRecordServiceServer) DeleteMapOfWorry(context.Context, *DeleteMapOfWorryRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMapOfWorry not implemented")
}
func (UnimplementedRecordServiceServer) ListBiases(context.Context, *ListBiasesRequest) (*ListBiasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBiases not implemented")
}
func (UnimplementedRecordServiceServer) CreateBias(context.Context, *CreateBiasRequest) (*CognitiveBias, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBias not implemented")
}
func (UnimplementedRecordServiceServer) RenameBias(context.Context, *RenameBiasRequest) (*CognitiveBias, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameBias not implemented")
}
func (UnimplementedRecordServiceServer) DeleteBias(context.Context, *DeleteBiasRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBias not implemented")
}
func (UnimplementedRecordServiceServer) mustEmbedUnimplementedRecordServiceServer() {}
func (UnimplementedRecordServiceServer) testEmbeddedByValue()                       {}

// UnsafeRecordServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordServiceServer will
// result in compilation errors.
type UnsafeRecordServiceServer interface {
	mustEmbedUnimplementedRecordServiceServer()
}

func RegisterRecordServiceServer(s grpc.ServiceRegistrar, srv RecordServiceServer) {
	// If the following call panics, it indicates UnimplementedRecordServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordService_ServiceDesc, srv)
}

func _RecordService_ListThoughtRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListThoughtRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).ListThoughtRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_ListThoughtRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).ListThoughtRecords(ctx, req.(*ListThoughtRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_CreateThoughtRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateThoughtRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).CreateThoughtRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_CreateThoughtRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).CreateThoughtRecord(ctx, req.(*CreateThoughtRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_GetThoughtRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThoughtRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).GetThoughtRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_GetThoughtRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).GetThoughtRecord(ctx, req.(*GetThoughtRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_UpdateThoughtRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateThoughtRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).UpdateThoughtRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_UpdateThoughtRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).UpdateThoughtRecord(ctx, req.(*UpdateThoughtRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_ChallengeThoughtRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChallengeThoughtRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).ChallengeThoughtRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_ChallengeThoughtRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).ChallengeThoughtRecord(ctx, req.(*ChallengeThoughtRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_DeleteThoughtRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteThoughtRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).DeleteThoughtRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_DeleteThoughtRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).DeleteThoughtRecord(ctx, req.(*DeleteThoughtRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_AddThought_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddThoughtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).AddThought(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_AddThought_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).AddThought(ctx, req.(*AddThoughtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_UpdateThought_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateThoughtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).UpdateThought(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_UpdateThought_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).UpdateThought(ctx, req.(*UpdateThoughtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_SetHotThought_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHotThoughtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).SetHotThought(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_SetHotThought_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).SetHotThought(ctx, req.(*SetHotThoughtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_SetThoughtFactual_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetThoughtFactualRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).SetThoughtFactual(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_SetThoughtFactual_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).SetThoughtFactual(ctx, req.(*SetThoughtFactualRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_DeleteThought_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteThoughtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).DeleteThought(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_DeleteThought_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).DeleteThought(ctx, req.(*DeleteThoughtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_AddFeeling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFeelingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).AddFeeling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_AddFeeling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).AddFeeling(ctx, req.(*AddFeelingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_AddMapFeeling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMapFeelingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).AddMapFeeling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_AddMapFeeling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).AddMapFeeling(ctx, req.(*AddMapFeelingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_DeleteFeeling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeelingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).DeleteFeeling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_DeleteFeeling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).DeleteFeeling(ctx, req.(*DeleteFeelingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_ListMapsOfWorry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMapsOfWorryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).ListMapsOfWorry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_ListMapsOfWorry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).ListMapsOfWorry(ctx, req.(*ListMapsOfWorryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_CreateMapOfWorry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMapOfWorryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).CreateMapOfWorry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_CreateMapOfWorry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).CreateMapOfWorry(ctx, req.(*CreateMapOfWorryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_GetMapOfWorry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMapOfWorryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).GetMapOfWorry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_GetMapOfWorry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).GetMapOfWorry(ctx, req.(*GetMapOfWorryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_UpdateMapOfWorry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMapOfWorryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).UpdateMapOfWorry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_UpdateMapOfWorry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).UpdateMapOfWorry(ctx, req.(*UpdateMapOfWorryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_DeleteMapOfWorry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMapOfWorryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).DeleteMapOfWorry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_DeleteMapOfWorry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).DeleteMapOfWorry(ctx, req.(*DeleteMapOfWorryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_ListBiases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBiasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).ListBiases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_ListBiases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).ListBiases(ctx, req.(*ListBiasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_CreateBias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBiasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).CreateBias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_CreateBias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).CreateBias(ctx, req.(*CreateBiasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_RenameBias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameBiasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).RenameBias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_RenameBias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).RenameBias(ctx, req.(*RenameBiasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_DeleteBias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBiasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).DeleteBias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordService_DeleteBias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).DeleteBias(ctx, req.(*DeleteBiasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordService_ServiceDesc is the grpc.ServiceDesc for RecordService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "record.RecordService",
	HandlerType: (*RecordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListThoughtRecords",
			Handler:    _RecordService_ListThoughtRecords_Handler,
		},
		{
			MethodName: "CreateThoughtRecord",
			Handler:    _RecordService_CreateThoughtRecord_Handler,
		},
		{
			MethodName: "GetThoughtRecord",
			Handler:    _RecordService_GetThoughtRecord_Handler,
		},
		{
			MethodName: "UpdateThoughtRecord",
			Handler:    _RecordService_UpdateThoughtRecord_Handler,
		},
		{
			MethodName: "ChallengeThoughtRecord",
			Handler:    _RecordService_ChallengeThoughtRecord_Handler,
		},
		{
			MethodName: "DeleteThoughtRecord",
			Handler:    _RecordService_DeleteThoughtRecord_Handler,
		},
		{
			MethodName: "AddThought",
			Handler:    _RecordService_AddThought_Handler,
		},
		{
			MethodName: "UpdateThought",
			Handler:    _RecordService_UpdateThought_Handler,
		},
		{
			MethodName: "SetHotThought",
			Handler:    _RecordService_SetHotThought_Handler,
		},
		{
			MethodName: "SetThoughtFactual",
			Handler:    _RecordService_SetThoughtFactual_Handler,
		},
		{
			MethodName: "DeleteThought",
			Handler:    _RecordService_DeleteThought_Handler,
		},
		{
			MethodName: "AddFeeling",
			Handler:    _RecordService_AddFeeling_Handler,
		},
		{
			MethodName: "AddMapFeeling",
			Handler:    _RecordService_AddMapFeeling_Handler,
		},
		{
			MethodName: "DeleteFeeling",
			Handler:    _RecordService_DeleteFeeling_Handler,
		},
		{
			MethodName: "ListMapsOfWorry",
			Handler:    _RecordService_ListMapsOfWorry_Handler,
		},
		{
			MethodName: "CreateMapOfWorry",
			Handler:    _RecordService_CreateMapOfWorry_Handler,
		},
		{
			MethodName: "GetMapOfWorry",
			Handler:    _RecordService_GetMapOfWorry_Handler,
		},
		{
			MethodName: "UpdateMapOfWorry",
			Handler:    _RecordService_UpdateMapOfWorry_Handler,
		},
		{
			MethodName: "DeleteMapOfWorry",
			Handler:    _RecordService_DeleteMapOfWorry_Handler,
		},
		{
			MethodName: "ListBiases",
			Handler:    _RecordService_ListBiases_Handler,
		},
		{
			MethodName: "CreateBias",
			Handler:    _RecordService_CreateBias_Handler,
		},
		{
			MethodName: "RenameBias",
			Handler:    _RecordService_RenameBias_Handler,
		},
		{
			MethodName: "DeleteBias",
			Handler:    _RecordService_DeleteBias_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/record.proto",
}
