// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: proto/record.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CognitiveBias is a named thinking error. The nine biases catalogued in the
// source material are seeded per user and marked builtin; builtins cannot be
// renamed or deleted.
type CognitiveBias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsBuiltin     bool                   `protobuf:"varint,3,opt,name=is_builtin,json=isBuiltin,proto3" json:"is_builtin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CognitiveBias) Reset() {
	*x = CognitiveBias{}
	mi := &file_proto_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CognitiveBias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CognitiveBias) ProtoMessage() {}

func (x *CognitiveBias) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CognitiveBias.ProtoReflect.Descriptor instead.
func (*CognitiveBias) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{0}
}

func (x *CognitiveBias) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CognitiveBias) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CognitiveBias) GetIsBuiltin() bool {
	if x != nil {
		return x.IsBuiltin
	}
	return false
}

// NegativeThought is a single negative automatic thought recorded against a
// thought record.
type NegativeThought struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Body  string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// is_hot marks the strongest thought of the record, the one worth
	// challenging first. At most one thought per record carries it.
	IsHot bool `protobuf:"varint,3,opt,name=is_hot,json=isHot,proto3" json:"is_hot,omitempty"`
	// biases are the thinking errors identified in this thought. The bias
	// belongs to the thought rather than the record because each thought carries
	// its own distortion.
	Biases []*CognitiveBias `protobuf:"bytes,4,rep,name=biases,proto3" json:"biases,omitempty"`
	// parent_id links this thought to the thought whose meaning it is, forming
	// the chain produced by the downward arrow technique. No RPC populates it
	// yet; the field is reserved so the chain can be recorded later.
	ParentId *uint32 `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	// is_factual records that the thought was examined and judged an accurate
	// reading of the situation rather than a distorted one. It cannot be
	// inferred from carrying no biases, because that is the state every thought
	// starts in. A thought that is factual never carries a bias.
	IsFactual     bool `protobuf:"varint,6,opt,name=is_factual,json=isFactual,proto3" json:"is_factual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NegativeThought) Reset() {
	*x = NegativeThought{}
	mi := &file_proto_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NegativeThought) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegativeThought) ProtoMessage() {}

func (x *NegativeThought) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegativeThought.ProtoReflect.Descriptor instead.
func (*NegativeThought) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{1}
}

func (x *NegativeThought) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NegativeThought) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NegativeThought) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *NegativeThought) GetBiases() []*CognitiveBias {
	if x != nil {
		return x.Biases
	}
	return nil
}

func (x *NegativeThought) GetParentId() uint32 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *NegativeThought) GetIsFactual() bool {
	if x != nil {
		return x.IsFactual
	}
	return false
}

// Feeling is a single emotion rated on a 0-100 scale.
type Feeling struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// intensity_before is the rating given when the feeling was recorded.
	IntensityBefore *int32 `protobuf:"varint,3,opt,name=intensity_before,json=intensityBefore,proto3,oneof" json:"intensity_before,omitempty"`
	// intensity_after is the re-rating given during the challenge. It is only
	// ever set on feelings belonging to a thought record.
	IntensityAfter *int32 `protobuf:"varint,4,opt,name=intensity_after,json=intensityAfter,proto3,oneof" json:"intensity_after,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Feeling) Reset() {
	*x = Feeling{}
	mi := &file_proto_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feeling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feeling) ProtoMessage() {}

func (x *Feeling) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feeling.ProtoReflect.Descriptor instead.
func (*Feeling) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{2}
}

func (x *Feeling) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Feeling) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Feeling) GetIntensityBefore() int32 {
	if x != nil && x.IntensityBefore != nil {
		return *x.IntensityBefore
	}
	return 0
}

func (x *Feeling) GetIntensityAfter() int32 {
	if x != nil && x.IntensityAfter != nil {
		return *x.IntensityAfter
	}
	return 0
}

// ThoughtRecord is the six column thought record: event, negative thought(s),
// negative feeling(s), cognitive bias, "is there any other way I can look at
// this?", and "how do I feel now?".
type ThoughtRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Event string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// occurred_at is when the event happened, which is frequently not when the
	// record was typed. It is absent when the user did not say.
	OccurredAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3,oneof" json:"occurred_at,omitempty"`
	AlternativeView string                 `protobuf:"bytes,4,opt,name=alternative_view,json=alternativeView,proto3" json:"alternative_view,omitempty"`
	FeelingsNow     string                 `protobuf:"bytes,5,opt,name=feelings_now,json=feelingsNow,proto3" json:"feelings_now,omitempty"`
	// challenged_at is set once the second sitting has happened, and absent
	// while the record is still in the work queue.
	ChallengedAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=challenged_at,json=challengedAt,proto3,oneof" json:"challenged_at,omitempty"`
	Thoughts      []*NegativeThought     `protobuf:"bytes,7,rep,name=thoughts,proto3" json:"thoughts,omitempty"`
	Feelings      []*Feeling             `protobuf:"bytes,8,rep,name=feelings,proto3" json:"feelings,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThoughtRecord) Reset() {
	*x = ThoughtRecord{}
	mi := &file_proto_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThoughtRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThoughtRecord) ProtoMessage() {}

func (x *ThoughtRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThoughtRecord.ProtoReflect.Descriptor instead.
func (*ThoughtRecord) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{3}
}

func (x *ThoughtRecord) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ThoughtRecord) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ThoughtRecord) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *ThoughtRecord) GetAlternativeView() string {
	if x != nil {
		return x.AlternativeView
	}
	return ""
}

func (x *ThoughtRecord) GetFeelingsNow() string {
	if x != nil {
		return x.FeelingsNow
	}
	return ""
}

func (x *ThoughtRecord) GetChallengedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChallengedAt
	}
	return nil
}

func (x *ThoughtRecord) GetThoughts() []*NegativeThought {
	if x != nil {
		return x.Thoughts
	}
	return nil
}

func (x *ThoughtRecord) GetFeelings() []*Feeling {
	if x != nil {
		return x.Feelings
	}
	return nil
}

func (x *ThoughtRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ThoughtRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// MapOfWorry traces a single event through to the behaviour it produced.
type MapOfWorry struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Event                 string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	OccurredAt            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3,oneof" json:"occurred_at,omitempty"`
	Thoughts              string                 `protobuf:"bytes,4,opt,name=thoughts,proto3" json:"thoughts,omitempty"`
	WhatTheseThoughtsMean string                 `protobuf:"bytes,5,opt,name=what_these_thoughts_mean,json=whatTheseThoughtsMean,proto3" json:"what_these_thoughts_mean,omitempty"`
	PhysicalSensations    string                 `protobuf:"bytes,6,opt,name=physical_sensations,json=physicalSensations,proto3" json:"physical_sensations,omitempty"`
	ResultantBehaviour    string                 `protobuf:"bytes,7,opt,name=resultant_behaviour,json=resultantBehaviour,proto3" json:"resultant_behaviour,omitempty"`
	// derived_from_id points at the map this one reworks. The contrast between
	// the two is the therapeutic payload, so they are read side by side.
	DerivedFromId *uint32                `protobuf:"varint,8,opt,name=derived_from_id,json=derivedFromId,proto3,oneof" json:"derived_from_id,omitempty"`
	Feelings      []*Feeling             `protobuf:"bytes,9,rep,name=feelings,proto3" json:"feelings,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapOfWorry) Reset() {
	*x = MapOfWorry{}
	mi := &file_proto_record_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapOfWorry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapOfWorry) ProtoMessage() {}

func (x *MapOfWorry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapOfWorry.ProtoReflect.Descriptor instead.
func (*MapOfWorry) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{4}
}

func (x *MapOfWorry) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MapOfWorry) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *MapOfWorry) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *MapOfWorry) GetThoughts() string {
	if x != nil {
		return x.Thoughts
	}
	return ""
}

func (x *MapOfWorry) GetWhatTheseThoughtsMean() string {
	if x != nil {
		return x.WhatTheseThoughtsMean
	}
	return ""
}

func (x *MapOfWorry) GetPhysicalSensations() string {
	if x != nil {
		return x.PhysicalSensations
	}
	return ""
}

func (x *MapOfWorry) GetResultantBehaviour() string {
	if x != nil {
		return x.ResultantBehaviour
	}
	return ""
}

func (x *MapOfWorry) GetDerivedFromId() uint32 {
	if x != nil && x.DerivedFromId != nil {
		return *x.DerivedFromId
	}
	return 0
}

func (x *MapOfWorry) GetFeelings() []*Feeling {
	if x != nil {
		return x.Feelings
	}
	return nil
}

func (x *MapOfWorry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MapOfWorry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// FeelingInput is a feeling as supplied by the client: a name and an optional
// 0-100 rating.
type FeelingInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Intensity     *int32                 `protobuf:"varint,2,opt,name=intensity,proto3,oneof" json:"intensity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeelingInput) Reset() {
	*x = FeelingInput{}
	mi := &file_proto_record_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeelingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeelingInput) ProtoMessage() {}

func (x *FeelingInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeelingInput.ProtoReflect.Descriptor instead.
func (*FeelingInput) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{5}
}

func (x *FeelingInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeelingInput) GetIntensity() int32 {
	if x != nil && x.Intensity != nil {
		return *x.Intensity
	}
	return 0
}

// ThoughtInput is a negative automatic thought as supplied by the client.
type ThoughtInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Body  string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	IsHot bool                   `protobuf:"varint,2,opt,name=is_hot,json=isHot,proto3" json:"is_hot,omitempty"`
	// biases must already exist. A bias is a vocabulary term rather than a free
	// tag, so an unrecognised name is reported as a typo rather than coined.
	Biases        []string `protobuf:"bytes,3,rep,name=biases,proto3" json:"biases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThoughtInput) Reset() {
	*x = ThoughtInput{}
	mi := &file_proto_record_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThoughtInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThoughtInput) ProtoMessage() {}

func (x *ThoughtInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThoughtInput.ProtoReflect.Descriptor instead.
func (*ThoughtInput) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{6}
}

func (x *ThoughtInput) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ThoughtInput) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *ThoughtInput) GetBiases() []string {
	if x != nil {
		return x.Biases
	}
	return nil
}

type ListThoughtRecordsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// challenged filters by whether the record has been challenged. Absent
	// returns both; false is the day's work queue.
	Challenged *bool `protobuf:"varint,1,opt,name=challenged,proto3,oneof" json:"challenged,omitempty"`
	// since restricts the listing to records whose event occurred on or after
	// this instant.
	Since *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3,oneof" json:"since,omitempty"`
	// search matches the event, the alternative view and the thought bodies.
	Search        string `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThoughtRecordsRequest) Reset() {
	*x = ListThoughtRecordsRequest{}
	mi := &file_proto_record_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThoughtRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThoughtRecordsRequest) ProtoMessage() {}

func (x *ListThoughtRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThoughtRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListThoughtRecordsRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{7}
}

func (x *ListThoughtRecordsRequest) GetChallenged() bool {
	if x != nil && x.Challenged != nil {
		return *x.Challenged
	}
	return false
}

func (x *ListThoughtRecordsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ListThoughtRecordsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListThoughtRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*ThoughtRecord       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThoughtRecordsResponse) Reset() {
	*x = ListThoughtRecordsResponse{}
	mi := &file_proto_record_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThoughtRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThoughtRecordsResponse) ProtoMessage() {}

func (x *ListThoughtRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThoughtRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListThoughtRecordsResponse) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{8}
}

func (x *ListThoughtRecordsResponse) GetRecords() []*ThoughtRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type CreateThoughtRecordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Event           string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	OccurredAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3,oneof" json:"occurred_at,omitempty"`
	AlternativeView string                 `protobuf:"bytes,3,opt,name=alternative_view,json=alternativeView,proto3" json:"alternative_view,omitempty"`
	FeelingsNow     string                 `protobuf:"bytes,4,opt,name=feelings_now,json=feelingsNow,proto3" json:"feelings_now,omitempty"`
	Thoughts        []*ThoughtInput        `protobuf:"bytes,5,rep,name=thoughts,proto3" json:"thoughts,omitempty"`
	Feelings        []*FeelingInput        `protobuf:"bytes,6,rep,name=feelings,proto3" json:"feelings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateThoughtRecordRequest) Reset() {
	*x = CreateThoughtRecordRequest{}
	mi := &file_proto_record_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateThoughtRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateThoughtRecordRequest) ProtoMessage() {}

func (x *CreateThoughtRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateThoughtRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateThoughtRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{9}
}

func (x *CreateThoughtRecordRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *CreateThoughtRecordRequest) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *CreateThoughtRecordRequest) GetAlternativeView() string {
	if x != nil {
		return x.AlternativeView
	}
	return ""
}

func (x *CreateThoughtRecordRequest) GetFeelingsNow() string {
	if x != nil {
		return x.FeelingsNow
	}
	return ""
}

func (x *CreateThoughtRecordRequest) GetThoughts() []*ThoughtInput {
	if x != nil {
		return x.Thoughts
	}
	return nil
}

func (x *CreateThoughtRecordRequest) GetFeelings() []*FeelingInput {
	if x != nil {
		return x.Feelings
	}
	return nil
}

type GetThoughtRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThoughtRecordRequest) Reset() {
	*x = GetThoughtRecordRequest{}
	mi := &file_proto_record_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThoughtRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThoughtRecordRequest) ProtoMessage() {}

func (x *GetThoughtRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThoughtRecordRequest.ProtoReflect.Descriptor instead.
func (*GetThoughtRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{10}
}

func (x *GetThoughtRecordRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateThoughtRecordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unset fields keep their current value, which is what allows a record to be
	// completed one column at a time.
	Event      *string                `protobuf:"bytes,2,opt,name=event,proto3,oneof" json:"event,omitempty"`
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3,oneof" json:"occurred_at,omitempty"`
	// clear_occurred_at distinguishes "leave the event time alone" from "forget
	// when it happened", which an absent occurred_at alone cannot express.
	ClearOccurredAt bool    `protobuf:"varint,4,opt,name=clear_occurred_at,json=clearOccurredAt,proto3" json:"clear_occurred_at,omitempty"`
	AlternativeView *string `protobuf:"bytes,5,opt,name=alternative_view,json=alternativeView,proto3,oneof" json:"alternative_view,omitempty"`
	FeelingsNow     *string `protobuf:"bytes,6,opt,name=feelings_now,json=feelingsNow,proto3,oneof" json:"feelings_now,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateThoughtRecordRequest) Reset() {
	*x = UpdateThoughtRecordRequest{}
	mi := &file_proto_record_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateThoughtRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateThoughtRecordRequest) ProtoMessage() {}

func (x *UpdateThoughtRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateThoughtRecordRequest.ProtoReflect.Descriptor instead.
func (*UpdateThoughtRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateThoughtRecordRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateThoughtRecordRequest) GetEvent() string {
	if x != nil && x.Event != nil {
		return *x.Event
	}
	return ""
}

func (x *UpdateThoughtRecordRequest) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *UpdateThoughtRecordRequest) GetClearOccurredAt() bool {
	if x != nil {
		return x.ClearOccurredAt
	}
	return false
}

func (x *UpdateThoughtRecordRequest) GetAlternativeView() string {
	if x != nil && x.AlternativeView != nil {
		return *x.AlternativeView
	}
	return ""
}

func (x *UpdateThoughtRecordRequest) GetFeelingsNow() string {
	if x != nil && x.FeelingsNow != nil {
		return *x.FeelingsNow
	}
	return ""
}

// ThoughtJudgement is the outcome of examining one thought during the
// challenge: which distortions it carries, or that it carries none because the
// thought was an accurate reading of the situation.
type ThoughtJudgement struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ThoughtId uint32                 `protobuf:"varint,1,opt,name=thought_id,json=thoughtId,proto3" json:"thought_id,omitempty"`
	// biases replaces whatever the thought carried, so re-running a challenge
	// with a corrected list leaves the corrected list. Leaving it unset keeps
	// the existing biases, so a judgement can record only that a thought is
	// factual; setting it to an empty list detaches them all.
	Biases *BiasNames `protobuf:"bytes,2,opt,name=biases,proto3,oneof" json:"biases,omitempty"`
	// is_factual records that the thought was judged an accurate reading.
	// Marking a thought factual while it still carries a bias is rejected.
	IsFactual     bool `protobuf:"varint,3,opt,name=is_factual,json=isFactual,proto3" json:"is_factual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThoughtJudgement) Reset() {
	*x = ThoughtJudgement{}
	mi := &file_proto_record_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThoughtJudgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThoughtJudgement) ProtoMessage() {}

func (x *ThoughtJudgement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThoughtJudgement.ProtoReflect.Descriptor instead.
func (*ThoughtJudgement) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{12}
}

func (x *ThoughtJudgement) GetThoughtId() uint32 {
	if x != nil {
		return x.ThoughtId
	}
	return 0
}

func (x *ThoughtJudgement) GetBiases() *BiasNames {
	if x != nil {
		return x.Biases
	}
	return nil
}

func (x *ThoughtJudgement) GetIsFactual() bool {
	if x != nil {
		return x.IsFactual
	}
	return false
}

// FeelingRerating is the post-challenge rating of one feeling.
type FeelingRerating struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FeelingId      uint32                 `protobuf:"varint,1,opt,name=feeling_id,json=feelingId,proto3" json:"feeling_id,omitempty"`
	IntensityAfter int32                  `protobuf:"varint,2,opt,name=intensity_after,json=intensityAfter,proto3" json:"intensity_after,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FeelingRerating) Reset() {
	*x = FeelingRerating{}
	mi := &file_proto_record_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeelingRerating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeelingRerating) ProtoMessage() {}

func (x *FeelingRerating) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeelingRerating.ProtoReflect.Descriptor instead.
func (*FeelingRerating) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{13}
}

func (x *FeelingRerating) GetFeelingId() uint32 {
	if x != nil {
		return x.FeelingId
	}
	return 0
}

func (x *FeelingRerating) GetIntensityAfter() int32 {
	if x != nil {
		return x.IntensityAfter
	}
	return 0
}

type ChallengeThoughtRecordRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AlternativeView  string                 `protobuf:"bytes,2,opt,name=alternative_view,json=alternativeView,proto3" json:"alternative_view,omitempty"`
	FeelingsNow      string                 `protobuf:"bytes,3,opt,name=feelings_now,json=feelingsNow,proto3" json:"feelings_now,omitempty"`
	FeelingReratings []*FeelingRerating     `protobuf:"bytes,4,rep,name=feeling_reratings,json=feelingReratings,proto3" json:"feeling_reratings,omitempty"`
	Thoughts         []*ThoughtJudgement    `protobuf:"bytes,5,rep,name=thoughts,proto3" json:"thoughts,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChallengeThoughtRecordRequest) Reset() {
	*x = ChallengeThoughtRecordRequest{}
	mi := &file_proto_record_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeThoughtRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeThoughtRecordRequest) ProtoMessage() {}

func (x *ChallengeThoughtRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeThoughtRecordRequest.ProtoReflect.Descriptor instead.
func (*ChallengeThoughtRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{14}
}

func (x *ChallengeThoughtRecordRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChallengeThoughtRecordRequest) GetAlternativeView() string {
	if x != nil {
		return x.AlternativeView
	}
	return ""
}

func (x *ChallengeThoughtRecordRequest) GetFeelingsNow() string {
	if x != nil {
		return x.FeelingsNow
	}
	return ""
}

func (x *ChallengeThoughtRecordRequest) GetFeelingReratings() []*FeelingRerating {
	if x != nil {
		return x.FeelingReratings
	}
	return nil
}

func (x *ChallengeThoughtRecordRequest) GetThoughts() []*ThoughtJudgement {
	if x != nil {
		return x.Thoughts
	}
	return nil
}

type DeleteThoughtRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteThoughtRecordRequest) Reset() {
	*x = DeleteThoughtRecordRequest{}
	mi := &file_proto_record_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteThoughtRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteThoughtRecordRequest) ProtoMessage() {}

func (x *DeleteThoughtRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteThoughtRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteThoughtRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteThoughtRecordRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddThoughtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      uint32                 `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Thought       *ThoughtInput          `protobuf:"bytes,2,opt,name=thought,proto3" json:"thought,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddThoughtRequest) Reset() {
	*x = AddThoughtRequest{}
	mi := &file_proto_record_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddThoughtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddThoughtRequest) ProtoMessage() {}

func (x *AddThoughtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddThoughtRequest.ProtoReflect.Descriptor instead.
func (*AddThoughtRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{16}
}

func (x *AddThoughtRequest) GetRecordId() uint32 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *AddThoughtRequest) GetThought() *ThoughtInput {
	if x != nil {
		return x.Thought
	}
	return nil
}

type UpdateThoughtRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Body  string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// biases replaces the biases on the thought when set. Leaving it unset keeps
	// the existing biases, so the wording can be corrected without redoing the
	// bias work; setting it to an empty list detaches them all.
	Biases        *BiasNames `protobuf:"bytes,3,opt,name=biases,proto3,oneof" json:"biases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateThoughtRequest) Reset() {
	*x = UpdateThoughtRequest{}
	mi := &file_proto_record_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateThoughtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateThoughtRequest) ProtoMessage() {}

func (x *UpdateThoughtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateThoughtRequest.ProtoReflect.Descriptor instead.
func (*UpdateThoughtRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateThoughtRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateThoughtRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *UpdateThoughtRequest) GetBiases() *BiasNames {
	if x != nil {
		return x.Biases
	}
	return nil
}

// BiasNames wraps a repeated field so that "not given" can be told apart from
// "given as empty". proto3 cannot mark a repeated field optional.
type BiasNames struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BiasNames) Reset() {
	*x = BiasNames{}
	mi := &file_proto_record_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BiasNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiasNames) ProtoMessage() {}

func (x *BiasNames) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiasNames.ProtoReflect.Descriptor instead.
func (*BiasNames) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{18}
}

func (x *BiasNames) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type SetHotThoughtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHotThoughtRequest) Reset() {
	*x = SetHotThoughtRequest{}
	mi := &file_proto_record_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHotThoughtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHotThoughtRequest) ProtoMessage() {}

func (x *SetHotThoughtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHotThoughtRequest.ProtoReflect.Descriptor instead.
func (*SetHotThoughtRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{19}
}

func (x *SetHotThoughtRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SetThoughtFactualRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Factual       bool                   `protobuf:"varint,2,opt,name=factual,proto3" json:"factual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetThoughtFactualRequest) Reset() {
	*x = SetThoughtFactualRequest{}
	mi := &file_proto_record_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetThoughtFactualRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetThoughtFactualRequest) ProtoMessage() {}

func (x *SetThoughtFactualRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetThoughtFactualRequest.ProtoReflect.Descriptor instead.
func (*SetThoughtFactualRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{20}
}

func (x *SetThoughtFactualRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetThoughtFactualRequest) GetFactual() bool {
	if x != nil {
		return x.Factual
	}
	return false
}

type DeleteThoughtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteThoughtRequest) Reset() {
	*x = DeleteThoughtRequest{}
	mi := &file_proto_record_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteThoughtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteThoughtRequest) ProtoMessage() {}

func (x *DeleteThoughtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteThoughtRequest.ProtoReflect.Descriptor instead.
func (*DeleteThoughtRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteThoughtRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddFeelingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      uint32                 `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Feeling       *FeelingInput          `protobuf:"bytes,2,opt,name=feeling,proto3" json:"feeling,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFeelingRequest) Reset() {
	*x = AddFeelingRequest{}
	mi := &file_proto_record_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFeelingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFeelingRequest) ProtoMessage() {}

func (x *AddFeelingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFeelingRequest.ProtoReflect.Descriptor instead.
func (*AddFeelingRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{22}
}

func (x *AddFeelingRequest) GetRecordId() uint32 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *AddFeelingRequest) GetFeeling() *FeelingInput {
	if x != nil {
		return x.Feeling
	}
	return nil
}

type AddMapFeelingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         uint32                 `protobuf:"varint,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Feeling       *FeelingInput          `protobuf:"bytes,2,opt,name=feeling,proto3" json:"feeling,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMapFeelingRequest) Reset() {
	*x = AddMapFeelingRequest{}
	mi := &file_proto_record_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMapFeelingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMapFeelingRequest) ProtoMessage() {}

func (x *AddMapFeelingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMapFeelingRequest.ProtoReflect.Descriptor instead.
func (*AddMapFeelingRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{23}
}

func (x *AddMapFeelingRequest) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *AddMapFeelingRequest) GetFeeling() *FeelingInput {
	if x != nil {
		return x.Feeling
	}
	return nil
}

type DeleteFeelingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFeelingRequest) Reset() {
	*x = DeleteFeelingRequest{}
	mi := &file_proto_record_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFeelingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFeelingRequest) ProtoMessage() {}

func (x *DeleteFeelingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFeelingRequest.ProtoReflect.Descriptor instead.
func (*DeleteFeelingRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteFeelingRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListMapsOfWorryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=since,proto3,oneof" json:"since,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMapsOfWorryRequest) Reset() {
	*x = ListMapsOfWorryRequest{}
	mi := &file_proto_record_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMapsOfWorryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMapsOfWorryRequest) ProtoMessage() {}

func (x *ListMapsOfWorryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMapsOfWorryRequest.ProtoReflect.Descriptor instead.
func (*ListMapsOfWorryRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{25}
}

func (x *ListMapsOfWorryRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ListMapsOfWorryRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListMapsOfWorryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Maps          []*MapOfWorry          `protobuf:"bytes,1,rep,name=maps,proto3" json:"maps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMapsOfWorryResponse) Reset() {
	*x = ListMapsOfWorryResponse{}
	mi := &file_proto_record_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMapsOfWorryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMapsOfWorryResponse) ProtoMessage() {}

func (x *ListMapsOfWorryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMapsOfWorryResponse.ProtoReflect.Descriptor instead.
func (*ListMapsOfWorryResponse) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{26}
}

func (x *ListMapsOfWorryResponse) GetMaps() []*MapOfWorry {
	if x != nil {
		return x.Maps
	}
	return nil
}

type CreateMapOfWorryRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Event                 string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	OccurredAt            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3,oneof" json:"occurred_at,omitempty"`
	Thoughts              string                 `protobuf:"bytes,3,opt,name=thoughts,proto3" json:"thoughts,omitempty"`
	WhatTheseThoughtsMean string                 `protobuf:"bytes,4,opt,name=what_these_thoughts_mean,json=whatTheseThoughtsMean,proto3" json:"what_these_thoughts_mean,omitempty"`
	PhysicalSensations    string                 `protobuf:"bytes,5,opt,name=physical_sensations,json=physicalSensations,proto3" json:"physical_sensations,omitempty"`
	ResultantBehaviour    string                 `protobuf:"bytes,6,opt,name=resultant_behaviour,json=resultantBehaviour,proto3" json:"resultant_behaviour,omitempty"`
	DerivedFromId         *uint32                `protobuf:"varint,7,opt,name=derived_from_id,json=derivedFromId,proto3,oneof" json:"derived_from_id,omitempty"`
	Feelings              []*FeelingInput        `protobuf:"bytes,8,rep,name=feelings,proto3" json:"feelings,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateMapOfWorryRequest) Reset() {
	*x = CreateMapOfWorryRequest{}
	mi := &file_proto_record_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMapOfWorryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMapOfWorryRequest) ProtoMessage() {}

func (x *CreateMapOfWorryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMapOfWorryRequest.ProtoReflect.Descriptor instead.
func (*CreateMapOfWorryRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{27}
}

func (x *CreateMapOfWorryRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *CreateMapOfWorryRequest) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *CreateMapOfWorryRequest) GetThoughts() string {
	if x != nil {
		return x.Thoughts
	}
	return ""
}

func (x *CreateMapOfWorryRequest) GetWhatTheseThoughtsMean() string {
	if x != nil {
		return x.WhatTheseThoughtsMean
	}
	return ""
}

func (x *CreateMapOfWorryRequest) GetPhysicalSensations() string {
	if x != nil {
		return x.PhysicalSensations
	}
	return ""
}

func (x *CreateMapOfWorryRequest) GetResultantBehaviour() string {
	if x != nil {
		return x.ResultantBehaviour
	}
	return ""
}

func (x *CreateMapOfWorryRequest) GetDerivedFromId() uint32 {
	if x != nil && x.DerivedFromId != nil {
		return *x.DerivedFromId
	}
	return 0
}

func (x *CreateMapOfWorryRequest) GetFeelings() []*FeelingInput {
	if x != nil {
		return x.Feelings
	}
	return nil
}

type GetMapOfWorryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapOfWorryRequest) Reset() {
	*x = GetMapOfWorryRequest{}
	mi := &file_proto_record_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapOfWorryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapOfWorryRequest) ProtoMessage() {}

func (x *GetMapOfWorryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapOfWorryRequest.ProtoReflect.Descriptor instead.
func (*GetMapOfWorryRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{28}
}

func (x *GetMapOfWorryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetMapOfWorryResponse carries the map together with the maps it should be
// read against: the one it reworks, and the reworkings of it.
type GetMapOfWorryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Map   *MapOfWorry            `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	// derived_from is the map this one reworks, when it is an alternative.
	DerivedFrom *MapOfWorry `protobuf:"bytes,2,opt,name=derived_from,json=derivedFrom,proto3,oneof" json:"derived_from,omitempty"`
	// alternatives are the maps derived from this one.
	Alternatives  []*MapOfWorry `protobuf:"bytes,3,rep,name=alternatives,proto3" json:"alternatives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapOfWorryResponse) Reset() {
	*x = GetMapOfWorryResponse{}
	mi := &file_proto_record_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapOfWorryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapOfWorryResponse) ProtoMessage() {}

func (x *GetMapOfWorryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapOfWorryResponse.ProtoReflect.Descriptor instead.
func (*GetMapOfWorryResponse) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{29}
}

func (x *GetMapOfWorryResponse) GetMap() *MapOfWorry {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *GetMapOfWorryResponse) GetDerivedFrom() *MapOfWorry {
	if x != nil {
		return x.DerivedFrom
	}
	return nil
}

func (x *GetMapOfWorryResponse) GetAlternatives() []*MapOfWorry {
	if x != nil {
		return x.Alternatives
	}
	return nil
}

type UpdateMapOfWorryRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Event                 *string                `protobuf:"bytes,2,opt,name=event,proto3,oneof" json:"event,omitempty"`
	OccurredAt            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3,oneof" json:"occurred_at,omitempty"`
	ClearOccurredAt       bool                   `protobuf:"varint,4,opt,name=clear_occurred_at,json=clearOccurredAt,proto3" json:"clear_occurred_at,omitempty"`
	Thoughts              *string                `protobuf:"bytes,5,opt,name=thoughts,proto3,oneof" json:"thoughts,omitempty"`
	WhatTheseThoughtsMean *string                `protobuf:"bytes,6,opt,name=what_these_thoughts_mean,json=whatTheseThoughtsMean,proto3,oneof" json:"what_these_thoughts_mean,omitempty"`
	PhysicalSensations    *string                `protobuf:"bytes,7,opt,name=physical_sensations,json=physicalSensations,proto3,oneof" json:"physical_sensations,omitempty"`
	ResultantBehaviour    *string                `protobuf:"bytes,8,opt,name=resultant_behaviour,json=resultantBehaviour,proto3,oneof" json:"resultant_behaviour,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateMapOfWorryRequest) Reset() {
	*x = UpdateMapOfWorryRequest{}
	mi := &file_proto_record_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMapOfWorryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMapOfWorryRequest) ProtoMessage() {}

func (x *UpdateMapOfWorryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMapOfWorryRequest.ProtoReflect.Descriptor instead.
func (*UpdateMapOfWorryRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateMapOfWorryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMapOfWorryRequest) GetEvent() string {
	if x != nil && x.Event != nil {
		return *x.Event
	}
	return ""
}

func (x *UpdateMapOfWorryRequest) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *UpdateMapOfWorryRequest) GetClearOccurredAt() bool {
	if x != nil {
		return x.ClearOccurredAt
	}
	return false
}

func (x *UpdateMapOfWorryRequest) GetThoughts() string {
	if x != nil && x.Thoughts != nil {
		return *x.Thoughts
	}
	return ""
}

func (x *UpdateMapOfWorryRequest) GetWhatTheseThoughtsMean() string {
	if x != nil && x.WhatTheseThoughtsMean != nil {
		return *x.WhatTheseThoughtsMean
	}
	return ""
}

func (x *UpdateMapOfWorryRequest) GetPhysicalSensations() string {
	if x != nil && x.PhysicalSensations != nil {
		return *x.PhysicalSensations
	}
	return ""
}

func (x *UpdateMapOfWorryRequest) GetResultantBehaviour() string {
	if x != nil && x.ResultantBehaviour != nil {
		return *x.ResultantBehaviour
	}
	return ""
}

type DeleteMapOfWorryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMapOfWorryRequest) Reset() {
	*x = DeleteMapOfWorryRequest{}
	mi := &file_proto_record_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMapOfWorryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMapOfWorryRequest) ProtoMessage() {}

func (x *DeleteMapOfWorryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMapOfWorryRequest.ProtoReflect.Descriptor instead.
func (*DeleteMapOfWorryRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteMapOfWorryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListBiasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBiasesRequest) Reset() {
	*x = ListBiasesRequest{}
	mi := &file_proto_record_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBiasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBiasesRequest) ProtoMessage() {}

func (x *ListBiasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBiasesRequest.ProtoReflect.Descriptor instead.
func (*ListBiasesRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{32}
}

type ListBiasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Biases        []*CognitiveBias       `protobuf:"bytes,1,rep,name=biases,proto3" json:"biases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBiasesResponse) Reset() {
	*x = ListBiasesResponse{}
	mi := &file_proto_record_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBiasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBiasesResponse) ProtoMessage() {}

func (x *ListBiasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBiasesResponse.ProtoReflect.Descriptor instead.
func (*ListBiasesResponse) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{33}
}

func (x *ListBiasesResponse) GetBiases() []*CognitiveBias {
	if x != nil {
		return x.Biases
	}
	return nil
}

type CreateBiasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBiasRequest) Reset() {
	*x = CreateBiasRequest{}
	mi := &file_proto_record_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBiasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBiasRequest) ProtoMessage() {}

func (x *CreateBiasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBiasRequest.ProtoReflect.Descriptor instead.
func (*CreateBiasRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{34}
}

func (x *CreateBiasRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RenameBiasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameBiasRequest) Reset() {
	*x = RenameBiasRequest{}
	mi := &file_proto_record_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameBiasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameBiasRequest) ProtoMessage() {}

func (x *RenameBiasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameBiasRequest.ProtoReflect.Descriptor instead.
func (*RenameBiasRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{35}
}

func (x *RenameBiasRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RenameBiasRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteBiasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBiasRequest) Reset() {
	*x = DeleteBiasRequest{}
	mi := &file_proto_record_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBiasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBiasRequest) ProtoMessage() {}

func (x *DeleteBiasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBiasRequest.ProtoReflect.Descriptor instead.
func (*DeleteBiasRequest) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{36}
}

func (x *DeleteBiasRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_record_proto protoreflect.FileDescriptor

const file_proto_record_proto_rawDesc = "" +
	"\n" +
	"\x12proto/record.proto\x12\x06record\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n" +
	"\rCognitiveBias\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"is_builtin\x18\x03 \x01(\bR\tisBuiltin\"\xca\x01\n" +
	"\x0fNegativeThought\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x15\n" +
	"\x06is_hot\x18\x03 \x01(\bR\x05isHot\x12-\n" +
	"\x06biases\x18\x04 \x03(\v2\x15.record.CognitiveBiasR\x06biases\x12 \n" +
	"\tparent_id\x18\x05 \x01(\rH\x00R\bparentId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_factual\x18\x06 \x01(\bR\tisFactualB\f\n" +
	"\n" +
	"_parent_id\"\xb4\x01\n" +
	"\aFeeling\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x10intensity_before\x18\x03 \x01(\x05H\x00R\x0fintensityBefore\x88\x01\x01\x12,\n" +
	"\x0fintensity_after\x18\x04 \x01(\x05H\x01R\x0eintensityAfter\x88\x01\x01B\x13\n" +
	"\x11_intensity_beforeB\x12\n" +
	"\x10_intensity_after\"\x85\x04\n" +
	"\rThoughtRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12@\n" +
	"\voccurred_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"occurredAt\x88\x01\x01\x12)\n" +
	"\x10alternative_view\x18\x04 \x01(\tR\x0falternativeView\x12!\n" +
	"\ffeelings_now\x18\x05 \x01(\tR\vfeelingsNow\x12D\n" +
	"\rchallenged_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\fchallengedAt\x88\x01\x01\x123\n" +
	"\bthoughts\x18\a \x03(\v2\x17.record.NegativeThoughtR\bthoughts\x12+\n" +
	"\bfeelings\x18\b \x03(\v2\x0f.record.FeelingR\bfeelings\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_occurred_atB\x10\n" +
	"\x0e_challenged_at\"\x9f\x04\n" +
	"\n" +
	"MapOfWorry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12@\n" +
	"\voccurred_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"occurredAt\x88\x01\x01\x12\x1a\n" +
	"\bthoughts\x18\x04 \x01(\tR\bthoughts\x127\n" +
	"\x18what_these_thoughts_mean\x18\x05 \x01(\tR\x15whatTheseThoughtsMean\x12/\n" +
	"\x13physical_sensations\x18\x06 \x01(\tR\x12physicalSensations\x12/\n" +
	"\x13resultant_behaviour\x18\a \x01(\tR\x12resultantBehaviour\x12+\n" +
	"\x0fderived_from_id\x18\b \x01(\rH\x01R\rderivedFromId\x88\x01\x01\x12+\n" +
	"\bfeelings\x18\t \x03(\v2\x0f.record.FeelingR\bfeelings\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_occurred_atB\x12\n" +
	"\x10_derived_from_id\"S\n" +
	"\fFeelingInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\tintensity\x18\x02 \x01(\x05H\x00R\tintensity\x88\x01\x01B\f\n" +
	"\n" +
	"_intensity\"Q\n" +
	"\fThoughtInput\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\x12\x15\n" +
	"\x06is_hot\x18\x02 \x01(\bR\x05isHot\x12\x16\n" +
	"\x06biases\x18\x03 \x03(\tR\x06biases\"\xa8\x01\n" +
	"\x19ListThoughtRecordsRequest\x12#\n" +
	"\n" +
	"challenged\x18\x01 \x01(\bH\x00R\n" +
	"challenged\x88\x01\x01\x125\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x05since\x88\x01\x01\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06searchB\r\n" +
	"\v_challengedB\b\n" +
	"\x06_since\"M\n" +
	"\x1aListThoughtRecordsResponse\x12/\n" +
	"\arecords\x18\x01 \x03(\v2\x15.record.ThoughtRecordR\arecords\"\xb6\x02\n" +
	"\x1aCreateThoughtRecordRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12@\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"occurredAt\x88\x01\x01\x12)\n" +
	"\x10alternative_view\x18\x03 \x01(\tR\x0falternativeView\x12!\n" +
	"\ffeelings_now\x18\x04 \x01(\tR\vfeelingsNow\x120\n" +
	"\bthoughts\x18\x05 \x03(\v2\x14.record.ThoughtInputR\bthoughts\x120\n" +
	"\bfeelings\x18\x06 \x03(\v2\x14.record.FeelingInputR\bfeelingsB\x0e\n" +
	"\f_occurred_at\")\n" +
	"\x17GetThoughtRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xcd\x02\n" +
	"\x1aUpdateThoughtRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\x05event\x18\x02 \x01(\tH\x00R\x05event\x88\x01\x01\x12@\n" +
	"\voccurred_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"occurredAt\x88\x01\x01\x12*\n" +
	"\x11clear_occurred_at\x18\x04 \x01(\bR\x0fclearOccurredAt\x12.\n" +
	"\x10alternative_view\x18\x05 \x01(\tH\x02R\x0falternativeView\x88\x01\x01\x12&\n" +
	"\ffeelings_now\x18\x06 \x01(\tH\x03R\vfeelingsNow\x88\x01\x01B\b\n" +
	"\x06_eventB\x0e\n" +
	"\f_occurred_atB\x13\n" +
	"\x11_alternative_viewB\x0f\n" +
	"\r_feelings_now\"\x8b\x01\n" +
	"\x10ThoughtJudgement\x12\x1d\n" +
	"\n" +
	"thought_id\x18\x01 \x01(\rR\tthoughtId\x12.\n" +
	"\x06biases\x18\x02 \x01(\v2\x11.record.BiasNamesH\x00R\x06biases\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_factual\x18\x03 \x01(\bR\tisFactualB\t\n" +
	"\a_biases\"Y\n" +
	"\x0fFeelingRerating\x12\x1d\n" +
	"\n" +
	"feeling_id\x18\x01 \x01(\rR\tfeelingId\x12'\n" +
	"\x0fintensity_after\x18\x02 \x01(\x05R\x0eintensityAfter\"\xf9\x01\n" +
	"\x1dChallengeThoughtRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12)\n" +
	"\x10alternative_view\x18\x02 \x01(\tR\x0falternativeView\x12!\n" +
	"\ffeelings_now\x18\x03 \x01(\tR\vfeelingsNow\x12D\n" +
	"\x11feeling_reratings\x18\x04 \x03(\v2\x17.record.FeelingReratingR\x10feelingReratings\x124\n" +
	"\bthoughts\x18\x05 \x03(\v2\x18.record.ThoughtJudgementR\bthoughts\",\n" +
	"\x1aDeleteThoughtRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"`\n" +
	"\x11AddThoughtRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\rR\brecordId\x12.\n" +
	"\athought\x18\x02 \x01(\v2\x14.record.ThoughtInputR\athought\"u\n" +
	"\x14UpdateThoughtRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12.\n" +
	"\x06biases\x18\x03 \x01(\v2\x11.record.BiasNamesH\x00R\x06biases\x88\x01\x01B\t\n" +
	"\a_biases\"!\n" +
	"\tBiasNames\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"&\n" +
	"\x14SetHotThoughtRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"D\n" +
	"\x18SetThoughtFactualRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\afactual\x18\x02 \x01(\bR\afactual\"&\n" +
	"\x14DeleteThoughtRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"`\n" +
	"\x11AddFeelingRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\rR\brecordId\x12.\n" +
	"\afeeling\x18\x02 \x01(\v2\x14.record.FeelingInputR\afeeling\"]\n" +
	"\x14AddMapFeelingRequest\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\rR\x05mapId\x12.\n" +
	"\afeeling\x18\x02 \x01(\v2\x14.record.FeelingInputR\afeeling\"&\n" +
	"\x14DeleteFeelingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"q\n" +
	"\x16ListMapsOfWorryRequest\x125\n" +
	"\x05since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x05since\x88\x01\x01\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06searchB\b\n" +
	"\x06_since\"A\n" +
	"\x17ListMapsOfWorryResponse\x12&\n" +
	"\x04maps\x18\x01 \x03(\v2\x12.record.MapOfWorryR\x04maps\"\xab\x03\n" +
	"\x17CreateMapOfWorryRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12@\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"occurredAt\x88\x01\x01\x12\x1a\n" +
	"\bthoughts\x18\x03 \x01(\tR\bthoughts\x127\n" +
	"\x18what_these_thoughts_mean\x18\x04 \x01(\tR\x15whatTheseThoughtsMean\x12/\n" +
	"\x13physical_sensations\x18\x05 \x01(\tR\x12physicalSensations\x12/\n" +
	"\x13resultant_behaviour\x18\x06 \x01(\tR\x12resultantBehaviour\x12+\n" +
	"\x0fderived_from_id\x18\a \x01(\rH\x01R\rderivedFromId\x88\x01\x01\x120\n" +
	"\bfeelings\x18\b \x03(\v2\x14.record.FeelingInputR\bfeelingsB\x0e\n" +
	"\f_occurred_atB\x12\n" +
	"\x10_derived_from_id\"&\n" +
	"\x14GetMapOfWorryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xc2\x01\n" +
	"\x15GetMapOfWorryResponse\x12$\n" +
	"\x03map\x18\x01 \x01(\v2\x12.record.MapOfWorryR\x03map\x12:\n" +
	"\fderived_from\x18\x02 \x01(\v2\x12.record.MapOfWorryH\x00R\vderivedFrom\x88\x01\x01\x126\n" +
	"\falternatives\x18\x03 \x03(\v2\x12.record.MapOfWorryR\falternativesB\x0f\n" +
	"\r_derived_from\"\xf1\x03\n" +
	"\x17UpdateMapOfWorryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\x05event\x18\x02 \x01(\tH\x00R\x05event\x88\x01\x01\x12@\n" +
	"\voccurred_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"occurredAt\x88\x01\x01\x12*\n" +
	"\x11clear_occurred_at\x18\x04 \x01(\bR\x0fclearOccurredAt\x12\x1f\n" +
	"\bthoughts\x18\x05 \x01(\tH\x02R\bthoughts\x88\x01\x01\x12<\n" +
	"\x18what_these_thoughts_mean\x18\x06 \x01(\tH\x03R\x15whatTheseThoughtsMean\x88\x01\x01\x124\n" +
	"\x13physical_sensations\x18\a \x01(\tH\x04R\x12physicalSensations\x88\x01\x01\x124\n" +
	"\x13resultant_behaviour\x18\b \x01(\tH\x05R\x12resultantBehaviour\x88\x01\x01B\b\n" +
	"\x06_eventB\x0e\n" +
	"\f_occurred_atB\v\n" +
	"\t_thoughtsB\x1b\n" +
	"\x19_what_these_thoughts_meanB\x16\n" +
	"\x14_physical_sensationsB\x16\n" +
	"\x14_resultant_behaviour\")\n" +
	"\x17DeleteMapOfWorryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x13\n" +
	"\x11ListBiasesRequest\"C\n" +
	"\x12ListBiasesResponse\x12-\n" +
	"\x06biases\x18\x01 \x03(\v2\x15.record.CognitiveBiasR\x06biases\"'\n" +
	"\x11CreateBiasRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x11RenameBiasRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"#\n" +
	"\x11DeleteBiasRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id2\xb8\r\n" +
	"\rRecordService\x12[\n" +
	"\x12ListThoughtRecords\x12!.record.ListThoughtRecordsRequest\x1a\".record.ListThoughtRecordsResponse\x12P\n" +
	"\x13CreateThoughtRecord\x12\".record.CreateThoughtRecordRequest\x1a\x15.record.ThoughtRecord\x12J\n" +
	"\x10GetThoughtRecord\x12\x1f.record.GetThoughtRecordRequest\x1a\x15.record.ThoughtRecord\x12P\n" +
	"\x13UpdateThoughtRecord\x12\".record.UpdateThoughtRecordRequest\x1a\x15.record.ThoughtRecord\x12V\n" +
	"\x16ChallengeThoughtRecord\x12%.record.ChallengeThoughtRecordRequest\x1a\x15.record.ThoughtRecord\x12Q\n" +
	"\x13DeleteThoughtRecord\x12\".record.DeleteThoughtRecordRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\n" +
	"AddThought\x12\x19.record.AddThoughtRequest\x1a\x15.record.ThoughtRecord\x12D\n" +
	"\rUpdateThought\x12\x1c.record.UpdateThoughtRequest\x1a\x15.record.ThoughtRecord\x12D\n" +
	"\rSetHotThought\x12\x1c.record.SetHotThoughtRequest\x1a\x15.record.ThoughtRecord\x12L\n" +
	"\x11SetThoughtFactual\x12 .record.SetThoughtFactualRequest\x1a\x15.record.ThoughtRecord\x12D\n" +
	"\rDeleteThought\x12\x1c.record.DeleteThoughtRequest\x1a\x15.record.ThoughtRecord\x12>\n" +
	"\n" +
	"AddFeeling\x12\x19.record.AddFeelingRequest\x1a\x15.record.ThoughtRecord\x12A\n" +
	"\rAddMapFeeling\x12\x1c.record.AddMapFeelingRequest\x1a\x12.record.MapOfWorry\x12E\n" +
	"\rDeleteFeeling\x12\x1c.record.DeleteFeelingRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x0fListMapsOfWorry\x12\x1e.record.ListMapsOfWorryRequest\x1a\x1f.record.ListMapsOfWorryResponse\x12G\n" +
	"\x10CreateMapOfWorry\x12\x1f.record.CreateMapOfWorryRequest\x1a\x12.record.MapOfWorry\x12L\n" +
	"\rGetMapOfWorry\x12\x1c.record.GetMapOfWorryRequest\x1a\x1d.record.GetMapOfWorryResponse\x12G\n" +
	"\x10UpdateMapOfWorry\x12\x1f.record.UpdateMapOfWorryRequest\x1a\x12.record.MapOfWorry\x12K\n" +
	"\x10DeleteMapOfWorry\x12\x1f.record.DeleteMapOfWorryRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\n" +
	"ListBiases\x12\x19.record.ListBiasesRequest\x1a\x1a.record.ListBiasesResponse\x12>\n" +
	"\n" +
	"CreateBias\x12\x19.record.CreateBiasRequest\x1a\x15.record.CognitiveBias\x12>\n" +
	"\n" +
	"RenameBias\x12\x19.record.RenameBiasRequest\x1a\x15.record.CognitiveBias\x12?\n" +
	"\n" +
	"DeleteBias\x12\x19.record.DeleteBiasRequest\x1a\x16.google.protobuf.EmptyB\x1fZ\x1dgithub.com/alexhokl/cbt/protob\x06proto3"

var (
	file_proto_record_proto_rawDescOnce sync.Once
	file_proto_record_proto_rawDescData []byte
)

func file_proto_record_proto_rawDescGZIP() []byte {
	file_proto_record_proto_rawDescOnce.Do(func() {
		file_proto_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_record_proto_rawDesc), len(file_proto_record_proto_rawDesc)))
	})
	return file_proto_record_proto_rawDescData
}

var file_proto_record_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_proto_record_proto_goTypes = []any{
	(*CognitiveBias)(nil),                 // 0: record.CognitiveBias
	(*NegativeThought)(nil),               // 1: record.NegativeThought
	(*Feeling)(nil),                       // 2: record.Feeling
	(*ThoughtRecord)(nil),                 // 3: record.ThoughtRecord
	(*MapOfWorry)(nil),                    // 4: record.MapOfWorry
	(*FeelingInput)(nil),                  // 5: record.FeelingInput
	(*ThoughtInput)(nil),                  // 6: record.ThoughtInput
	(*ListThoughtRecordsRequest)(nil),     // 7: record.ListThoughtRecordsRequest
	(*ListThoughtRecordsResponse)(nil),    // 8: record.ListThoughtRecordsResponse
	(*CreateThoughtRecordRequest)(nil),    // 9: record.CreateThoughtRecordRequest
	(*GetThoughtRecordRequest)(nil),       // 10: record.GetThoughtRecordRequest
	(*UpdateThoughtRecordRequest)(nil),    // 11: record.UpdateThoughtRecordRequest
	(*ThoughtJudgement)(nil),              // 12: record.ThoughtJudgement
	(*FeelingRerating)(nil),               // 13: record.FeelingRerating
	(*ChallengeThoughtRecordRequest)(nil), // 14: record.ChallengeThoughtRecordRequest
	(*DeleteThoughtRecordRequest)(nil),    // 15: record.DeleteThoughtRecordRequest
	(*AddThoughtRequest)(nil),             // 16: record.AddThoughtRequest
	(*UpdateThoughtRequest)(nil),          // 17: record.UpdateThoughtRequest
	(*BiasNames)(nil),                     // 18: record.BiasNames
	(*SetHotThoughtRequest)(nil),          // 19: record.SetHotThoughtRequest
	(*SetThoughtFactualRequest)(nil),      // 20: record.SetThoughtFactualRequest
	(*DeleteThoughtRequest)(nil),          // 21: record.DeleteThoughtRequest
	(*AddFeelingRequest)(nil),             // 22: record.AddFeelingRequest
	(*AddMapFeelingRequest)(nil),          // 23: record.AddMapFeelingRequest
	(*DeleteFeelingRequest)(nil),          // 24: record.DeleteFeelingRequest
	(*ListMapsOfWorryRequest)(nil),        // 25: record.ListMapsOfWorryRequest
	(*ListMapsOfWorryResponse)(nil),       // 26: record.ListMapsOfWorryResponse
	(*CreateMapOfWorryRequest)(nil),       // 27: record.CreateMapOfWorryRequest
	(*GetMapOfWorryRequest)(nil),          // 28: record.GetMapOfWorryRequest
	(*GetMapOfWorryResponse)(nil),         // 29: record.GetMapOfWorryResponse
	(*UpdateMapOfWorryRequest)(nil),       // 30: record.UpdateMapOfWorryRequest
	(*DeleteMapOfWorryRequest)(nil),       // 31: record.DeleteMapOfWorryRequest
	(*ListBiasesRequest)(nil),             // 32: record.ListBiasesRequest
	(*ListBiasesResponse)(nil),            // 33: record.ListBiasesResponse
	(*CreateBiasRequest)(nil),             // 34: record.CreateBiasRequest
	(*RenameBiasRequest)(nil),             // 35: record.RenameBiasRequest
	(*DeleteBiasRequest)(nil),             // 36: record.DeleteBiasRequest
	(*timestamppb.Timestamp)(nil),         // 37: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 38: google.protobuf.Empty
}
var file_proto_record_proto_depIdxs = []int32{
	0,  // 0: record.NegativeThought.biases:type_name -> record.CognitiveBias
	37, // 1: record.ThoughtRecord.occurred_at:type_name -> google.protobuf.Timestamp
	37, // 2: record.ThoughtRecord.challenged_at:type_name -> google.protobuf.Timestamp
	1,  // 3: record.ThoughtRecord.thoughts:type_name -> record.NegativeThought
	2,  // 4: record.ThoughtRecord.feelings:type_name -> record.Feeling
	37, // 5: record.ThoughtRecord.created_at:type_name -> google.protobuf.Timestamp
	37, // 6: record.ThoughtRecord.updated_at:type_name -> google.protobuf.Timestamp
	37, // 7: record.MapOfWorry.occurred_at:type_name -> google.protobuf.Timestamp
	2,  // 8: record.MapOfWorry.feelings:type_name -> record.Feeling
	37, // 9: record.MapOfWorry.created_at:type_name -> google.protobuf.Timestamp
	37, // 10: record.MapOfWorry.updated_at:type_name -> google.protobuf.Timestamp
	37, // 11: record.ListThoughtRecordsRequest.since:type_name -> google.protobuf.Timestamp
	3,  // 12: record.ListThoughtRecordsResponse.records:type_name -> record.ThoughtRecord
	37, // 13: record.CreateThoughtRecordRequest.occurred_at:type_name -> google.protobuf.Timestamp
	6,  // 14: record.CreateThoughtRecordRequest.thoughts:type_name -> record.ThoughtInput
	5,  // 15: record.CreateThoughtRecordRequest.feelings:type_name -> record.FeelingInput
	37, // 16: record.UpdateThoughtRecordRequest.occurred_at:type_name -> google.protobuf.Timestamp
	18, // 17: record.ThoughtJudgement.biases:type_name -> record.BiasNames
	13, // 18: record.ChallengeThoughtRecordRequest.feeling_reratings:type_name -> record.FeelingRerating
	12, // 19: record.ChallengeThoughtRecordRequest.thoughts:type_name -> record.ThoughtJudgement
	6,  // 20: record.AddThoughtRequest.thought:type_name -> record.ThoughtInput
	18, // 21: record.UpdateThoughtRequest.biases:type_name -> record.BiasNames
	5,  // 22: record.AddFeelingRequest.feeling:type_name -> record.FeelingInput
	5,  // 23: record.AddMapFeelingRequest.feeling:type_name -> record.FeelingInput
	37, // 24: record.ListMapsOfWorryRequest.since:type_name -> google.protobuf.Timestamp
	4,  // 25: record.ListMapsOfWorryResponse.maps:type_name -> record.MapOfWorry
	37, // 26: record.CreateMapOfWorryRequest.occurred_at:type_name -> google.protobuf.Timestamp
	5,  // 27: record.CreateMapOfWorryRequest.feelings:type_name -> record.FeelingInput
	4,  // 28: record.GetMapOfWorryResponse.map:type_name -> record.MapOfWorry
	4,  // 29: record.GetMapOfWorryResponse.derived_from:type_name -> record.MapOfWorry
	4,  // 30: record.GetMapOfWorryResponse.alternatives:type_name -> record.MapOfWorry
	37, // 31: record.UpdateMapOfWorryRequest.occurred_at:type_name -> google.protobuf.Timestamp
	0,  // 32: record.ListBiasesResponse.biases:type_name -> record.CognitiveBias
	7,  // 33: record.RecordService.ListThoughtRecords:input_type -> record.ListThoughtRecordsRequest
	9,  // 34: record.RecordService.CreateThoughtRecord:input_type -> record.CreateThoughtRecordRequest
	10, // 35: record.RecordService.GetThoughtRecord:input_type -> record.GetThoughtRecordRequest
	11, // 36: record.RecordService.UpdateThoughtRecord:input_type -> record.UpdateThoughtRecordRequest
	14, // 37: record.RecordService.ChallengeThoughtRecord:input_type -> record.ChallengeThoughtRecordRequest
	15, // 38: record.RecordService.DeleteThoughtRecord:input_type -> record.DeleteThoughtRecordRequest
	16, // 39: record.RecordService.AddThought:input_type -> record.AddThoughtRequest
	17, // 40: record.RecordService.UpdateThought:input_type -> record.UpdateThoughtRequest
	19, // 41: record.RecordService.SetHotThought:input_type -> record.SetHotThoughtRequest
	20, // 42: record.RecordService.SetThoughtFactual:input_type -> record.SetThoughtFactualRequest
	21, // 43: record.RecordService.DeleteThought:input_type -> record.DeleteThoughtRequest
	22, // 44: record.RecordService.AddFeeling:input_type -> record.AddFeelingRequest
	23, // 45: record.RecordService.AddMapFeeling:input_type -> record.AddMapFeelingRequest
	24, // 46: record.RecordService.DeleteFeeling:input_type -> record.DeleteFeelingRequest
	25, // 47: record.RecordService.ListMapsOfWorry:input_type -> record.ListMapsOfWorryRequest
	27, // 48: record.RecordService.CreateMapOfWorry:input_type -> record.CreateMapOfWorryRequest
	28, // 49: record.RecordService.GetMapOfWorry:input_type -> record.GetMapOfWorryRequest
	30, // 50: record.RecordService.UpdateMapOfWorry:input_type -> record.UpdateMapOfWorryRequest
	31, // 51: record.RecordService.DeleteMapOfWorry:input_type -> record.DeleteMapOfWorryRequest
	32, // 52: record.RecordService.ListBiases:input_type -> record.ListBiasesRequest
	34, // 53: record.RecordService.CreateBias:input_type -> record.CreateBiasRequest
	35, // 54: record.RecordService.RenameBias:input_type -> record.RenameBiasRequest
	36, // 55: record.RecordService.DeleteBias:input_type -> record.DeleteBiasRequest
	8,  // 56: record.RecordService.ListThoughtRecords:output_type -> record.ListThoughtRecordsResponse
	3,  // 57: record.RecordService.CreateThoughtRecord:output_type -> record.ThoughtRecord
	3,  // 58: record.RecordService.GetThoughtRecord:output_type -> record.ThoughtRecord
	3,  // 59: record.RecordService.UpdateThoughtRecord:output_type -> record.ThoughtRecord
	3,  // 60: record.RecordService.ChallengeThoughtRecord:output_type -> record.ThoughtRecord
	38, // 61: record.RecordService.DeleteThoughtRecord:output_type -> google.protobuf.Empty
	3,  // 62: record.RecordService.AddThought:output_type -> record.ThoughtRecord
	3,  // 63: record.RecordService.UpdateThought:output_type -> record.ThoughtRecord
	3,  // 64: record.RecordService.SetHotThought:output_type -> record.ThoughtRecord
	3,  // 65: record.RecordService.SetThoughtFactual:output_type -> record.ThoughtRecord
	3,  // 66: record.RecordService.DeleteThought:output_type -> record.ThoughtRecord
	3,  // 67: record.RecordService.AddFeeling:output_type -> record.ThoughtRecord
	4,  // 68: record.RecordService.AddMapFeeling:output_type -> record.MapOfWorry
	38, // 69: record.RecordService.DeleteFeeling:output_type -> google.protobuf.Empty
	26, // 70: record.RecordService.ListMapsOfWorry:output_type -> record.ListMapsOfWorryResponse
	4,  // 71: record.RecordService.CreateMapOfWorry:output_type -> record.MapOfWorry
	29, // 72: record.RecordService.GetMapOfWorry:output_type -> record.GetMapOfWorryResponse
	4,  // 73: record.RecordService.UpdateMapOfWorry:output_type -> record.MapOfWorry
	38, // 74: record.RecordService.DeleteMapOfWorry:output_type -> google.protobuf.Empty
	33, // 75: record.RecordService.ListBiases:output_type -> record.ListBiasesResponse
	0,  // 76: record.RecordService.CreateBias:output_type -> record.CognitiveBias
	0,  // 77: record.RecordService.RenameBias:output_type -> record.CognitiveBias
	38, // 78: record.RecordService.DeleteBias:output_type -> google.protobuf.Empty
	56, // [56:79] is the sub-list for method output_type
	33, // [33:56] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_proto_record_proto_init() }
func file_proto_record_proto_init() {
	if File_proto_record_proto != nil {
		return
	}
	file_proto_record_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_record_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_record_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_record_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_record_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_record_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_record_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_record_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_record_proto_msgTypes[12].OneofWrappers = []any{}
	file_proto_record_proto_msgTypes[17].OneofWrappers = []any{}
	file_proto_record_proto_msgTypes[25].OneofWrappers = []any{}
	file_proto_record_proto_msgTypes[27].OneofWrappers = []any{}
	file_proto_record_proto_msgTypes[29].OneofWrappers = []any{}
	file_proto_record_proto_msgTypes[30].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_record_proto_rawDesc), len(file_proto_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_record_proto_goTypes,
		DependencyIndexes: file_proto_record_proto_depIdxs,
		MessageInfos:      file_proto_record_proto_msgTypes,
	}.Build()
	File_proto_record_proto = out.File
	file_proto_record_proto_goTypes = nil
	file_proto_record_proto_depIdxs = nil
}
