import 'package:flutter/material.dart';

import '../l10n/app_localizations.dart';
import '../proto/record.pb.dart';
import '../services/record_service.dart';
import 'settings_page.dart';

/// The questions the source material suggests for finding an alternative
/// thought. They are shown as prompts, not as fields to fill in: the answer
/// goes into the one alternative view box, and the questions are only there to
/// get it started.
///
/// These are quotations from the method, not advice generated by the
/// application. Nothing here interprets what the user wrote.
const List<String> challengeQuestions = <String>[
  'Is my first thought a fact or an assumption?',
  'If it is an assumption, might there be an alternative one?',
  'Have I had a similar experience before where I took a different view?',
  'Is there anything positive here that I am discounting?',
  'If a friend told me they had this worry, what would I say to them?',
  'What is the worst that could happen if the thought is correct?',
  'Could I cope with it? Would it really change my life?',
  'Would I still care about this in a few years?',
];

/// ChallengePage records the second sitting of a thought record.
///
/// The record as written is shown read only at the top: the point of the
/// exercise is to read back what you thought at the time and answer against
/// it, so it must not be editable here. Editing belongs on the edit page.
class ChallengePage extends StatefulWidget {
  const ChallengePage({super.key, required this.record, this.service});

  final ThoughtRecord record;
  final RecordService? service;

  @override
  State<ChallengePage> createState() => _ChallengePageState();
}

class _ChallengePageState extends State<ChallengePage> {
  final TextEditingController _alternativeController = TextEditingController();
  final TextEditingController _feelingsNowController = TextEditingController();

  /// The biases selected for each thought, keyed by thought id. The selection
  /// replaces whatever the thought carried, so coming back with a corrected
  /// list leaves the corrected list.
  final Map<int, Set<String>> _thoughtBiases = <int, Set<String>>{};

  /// Whether each thought was judged an accurate reading of the situation,
  /// keyed by thought id. A thought is never both accurate and distorted, so
  /// turning this on clears the chips rather than leaving the server to refuse
  /// a request the screen should not have allowed to be built.
  final Map<int, bool> _thoughtFactual = <int, bool>{};

  /// The re-rating of each feeling, keyed by feeling id. A feeling starts at
  /// its original rating so an untouched slider records "unchanged" rather
  /// than silently dropping to zero.
  final Map<int, int> _reratings = <int, int>{};

  List<CognitiveBias> _biases = <CognitiveBias>[];
  bool _loading = true;
  bool _saving = false;
  String? _error;

  @override
  void initState() {
    super.initState();
    _alternativeController.text = widget.record.alternativeView;
    _feelingsNowController.text = widget.record.feelingsNow;
    for (final thought in widget.record.thoughts) {
      _thoughtBiases[thought.id] =
          thought.biases.map((bias) => bias.name).toSet();
      _thoughtFactual[thought.id] = thought.isFactual;
    }
    for (final feeling in widget.record.feelings) {
      _reratings[feeling.id] = feeling.hasIntensityAfter()
          ? feeling.intensityAfter
          : (feeling.hasIntensityBefore() ? feeling.intensityBefore : 0);
    }
    _loadBiases();
  }

  @override
  void dispose() {
    _alternativeController.dispose();
    _feelingsNowController.dispose();
    super.dispose();
  }

  Future<RecordService> _service() async =>
      widget.service ?? await BackendConfig.buildService();

  Future<void> _loadBiases() async {
    setState(() {
      _loading = true;
      _error = null;
    });
    try {
      final service = await _service();
      final biases = await service.listBiases();
      if (!mounted) return;
      setState(() {
        _biases = biases;
        _loading = false;
      });
    } on RecordException catch (error) {
      if (!mounted) return;
      setState(() {
        _error = error.message;
        _loading = false;
      });
    }
  }

  Future<void> _save() async {
    setState(() => _saving = true);

    final request = ChallengeThoughtRecordRequest()
      ..id = widget.record.id
      ..alternativeView = _alternativeController.text
      ..feelingsNow = _feelingsNowController.text;

    _reratings.forEach((feelingId, intensity) {
      request.feelingReratings.add(
        FeelingRerating()
          ..feelingId = feelingId
          ..intensityAfter = intensity,
      );
    });

    _thoughtBiases.forEach((thoughtId, names) {
      // The wrapper is always sent, including when empty: an absent wrapper
      // means "leave the biases alone", which is the opposite instruction.
      request.thoughts.add(
        ThoughtJudgement()
          ..thoughtId = thoughtId
          ..biases = (BiasNames()..names.addAll(names))
          ..isFactual = _thoughtFactual[thoughtId] ?? false,
      );
    });

    try {
      final service = await _service();
      await service.challengeThoughtRecord(request);
      if (!mounted) return;
      Navigator.of(context).pop();
    } on RecordException catch (error) {
      if (!mounted) return;
      setState(() => _saving = false);
      ScaffoldMessenger.of(context)
          .showSnackBar(SnackBar(content: Text(error.message)));
    }
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;

    return Scaffold(
      appBar: AppBar(title: Text(l10n.challengeTitle(widget.record.id))),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : _buildForm(l10n),
      bottomNavigationBar: _loading
          ? null
          : Padding(
              padding: const EdgeInsets.all(16),
              child: FilledButton(
                onPressed: _saving ? null : _save,
                child: Text(l10n.challengeSave),
              ),
            ),
    );
  }

  Widget _buildForm(AppLocalizations l10n) {
    return ListView(
      padding: const EdgeInsets.all(16),
      children: [
        Text(l10n.challengeIntro,
            style: Theme.of(context).textTheme.bodyMedium),
        const SizedBox(height: 16),

        // What was written at the time, read only.
        Card(
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(l10n.fieldEvent,
                    style: Theme.of(context).textTheme.labelMedium),
                const SizedBox(height: 4),
                Text(widget.record.event),
              ],
            ),
          ),
        ),

        if (_error != null) ...[
          const SizedBox(height: 16),
          Text(_error!),
        ],

        if (widget.record.thoughts.isNotEmpty) ...[
          const SizedBox(height: 24),
          Text(l10n.challengeStepBiases,
              style: Theme.of(context).textTheme.titleMedium),
          for (final thought in widget.record.thoughts)
            _thoughtBiasPicker(thought, l10n),
        ],

        const SizedBox(height: 24),
        Text(l10n.challengeStepAlternative,
            style: Theme.of(context).textTheme.titleMedium),
        const SizedBox(height: 8),
        ExpansionTile(
          title: Text(l10n.challengeQuestionsTitle),
          children: [
            for (final question in challengeQuestions)
              ListTile(dense: true, title: Text(question)),
          ],
        ),
        const SizedBox(height: 8),
        TextField(
          key: const Key('alternativeView'),
          controller: _alternativeController,
          minLines: 4,
          maxLines: 10,
          decoration: const InputDecoration(border: OutlineInputBorder()),
        ),

        if (widget.record.feelings.isNotEmpty) ...[
          const SizedBox(height: 24),
          Text(l10n.challengeStepRerate,
              style: Theme.of(context).textTheme.titleMedium),
          for (final feeling in widget.record.feelings)
            _feelingRerater(feeling, l10n),
        ],

        const SizedBox(height: 24),
        Text(l10n.challengeStepFeelingsNow,
            style: Theme.of(context).textTheme.titleMedium),
        const SizedBox(height: 8),
        TextField(
          key: const Key('feelingsNow'),
          controller: _feelingsNowController,
          minLines: 2,
          maxLines: 6,
          decoration: const InputDecoration(border: OutlineInputBorder()),
        ),
      ],
    );
  }

  Widget _thoughtBiasPicker(NegativeThought thought, AppLocalizations l10n) {
    final selected = _thoughtBiases[thought.id] ?? <String>{};
    final isFactual = _thoughtFactual[thought.id] ?? false;

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(12),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                if (thought.isHot)
                  const Padding(
                    padding: EdgeInsets.only(right: 8),
                    child: Icon(Icons.local_fire_department_outlined, size: 18),
                  ),
                Expanded(child: Text(thought.body)),
              ],
            ),
            // Not every thought is distorted. Saying so is an outcome of the
            // exercise in its own right, so it is offered here rather than
            // being left to look like an unanswered question.
            SwitchListTile(
              contentPadding: EdgeInsets.zero,
              title: Text(l10n.thoughtIsFactual),
              value: isFactual,
              onChanged: (value) {
                setState(() {
                  _thoughtFactual[thought.id] = value;
                  if (value) {
                    selected.clear();
                    _thoughtBiases[thought.id] = selected;
                  }
                });
              },
            ),
            Wrap(
              spacing: 6,
              runSpacing: 4,
              children: [
                for (final bias in _biases)
                  FilterChip(
                    label: Text(bias.name),
                    selected: selected.contains(bias.name),
                    // Disabled rather than hidden, so the reason the chips
                    // cannot be used stays visible next to the switch.
                    onSelected: isFactual
                        ? null
                        : (isSelected) {
                            setState(() {
                              if (isSelected) {
                                selected.add(bias.name);
                              } else {
                                selected.remove(bias.name);
                              }
                              _thoughtBiases[thought.id] = selected;
                            });
                          },
                  ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _feelingRerater(Feeling feeling, AppLocalizations l10n) {
    final current = _reratings[feeling.id] ?? 0;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Expanded(child: Text(feeling.name)),
            // The original rating stays visible while re-rating: the change is
            // the thing worth seeing, not the new number on its own.
            if (feeling.hasIntensityBefore())
              Text('${feeling.intensityBefore}% → $current%')
            else
              Text('$current%'),
          ],
        ),
        Slider(
          value: current.toDouble(),
          min: 0,
          max: 100,
          divisions: 20,
          label: '$current%',
          onChanged: (value) =>
              setState(() => _reratings[feeling.id] = value.round()),
        ),
      ],
    );
  }
}
